color: null
fieldLayouts:
  64cf375e-c4a1-44ca-a9af-96b41426db96:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-05T07:24:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0b2a7b93-f5e9-44d3-bdde-4e2e40129ea0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-05T07:32:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6fa806b2-1372-4b59-921a-7414bf7345b9 # Rich Text
            handle: lead
            includeInCards: false
            instructions: null
            label: Lead
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cafd2bd-2bc3-484d-be14-fe6fe9b8fe40
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 88938610-e6e8-4596-92f8-0e14e93a4c27
        userCondition: null
handle: home
hasTitleField: true
icon: house
name: home
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
