color: null
fieldLayouts:
  9f9e8acf-0df9-4350-89df-b4dd0c762ffc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-05T09:08:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c4408594-be1a-4f8d-bc31-171582218b3c # Assets Image Multi
            handle: images
            includeInCards: false
            instructions: null
            label: Images
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7ed0213-ddff-4be4-ae34-d31091742891
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 23db242b-4181-4107-bc94-8bacb807ff67
        userCondition: null
handle: projectsContentBlocksImages
hasTitleField: false
icon: null
name: 'Projects - Content Blocks - Images'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
