color: null
fieldLayouts:
  bb655564-631e-4e80-9faf-0692c0b0c526:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-05T08:45:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3dfd67fd-bdbf-41b5-b412-e4731259bcfb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-05T09:09:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1b01d95f-9856-4142-ae9f-4b090c98a8b5 # Assets Image Single
            handle: previewImage
            includeInCards: false
            instructions: null
            label: 'Preview Image'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3017a15-4791-4eae-a910-1ad6cfa5d073
            userCondition: null
            warning: null
            width: 100
        name: Preview
        uid: 4dd95d9a-77d2-40aa-8356-fb6d7278e3cd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-05T09:09:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6c73dea-eb4d-42ff-a6db-4a3c30ae6062 # Projects - Content Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf713b85-f236-49bc-b892-860f220d7124
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85769217-cc7b-44d0-9400-831a582190e8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-05T10:49:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6fa806b2-1372-4b59-921a-7414bf7345b9 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66fb7637-f49a-4136-bf9d-8e8fb6a9a72d
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 9784a386-004b-45d6-96a2-6187b7e817e9
        userCondition: null
handle: projects
hasTitleField: true
icon: null
name: Projects
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
