color: null
fieldLayouts:
  77639c30-00f2-45c6-a9d7-4dd211d1e4f0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-05T07:32:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 70d3292e-8c71-4fb6-8721-8fb2d2c6a2ca
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 2e0739fa-484a-48f1-80f3-b4605f03f27d
        userCondition: null
handle: site
hasTitleField: true
icon: null
name: Site
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
