altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  5fe31722-dcfa-4e64-9ec3-d2ff852a1c50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-05T07:17:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4a6bb465-723b-4cf5-b42a-d9e3ee2f9e1b
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 43cc60b8-4c05-4824-ad9d-f5f17bdf5730
        userCondition: null
fs: public
handle: public
name: Public
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: _transforms
