columnSuffix: null
handle: switchOn
instructions: null
name: 'Switch On'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
