dateModified: 1746428506
email:
  fromEmail: info@jografix.ch
  fromName: jografix
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5a939ab0-73c5-4be1-a179-c17821614719: jografix # jografix
    969c9c0a-6b56-436e-a99e-546445324e12: jografix # jografix
system:
  edition: solo
  live: true
  name: jografix
  schemaVersion: 5.7.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
