defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d1905640-7842-4e3b-85dd-eff015061a6c # Site
handle: site
maxAuthors: 1
name: Site
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre Eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5a939ab0-73c5-4be1-a179-c17821614719: # jografix
    enabledByDefault: true
    hasUrls: true
    template: site/_entry.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 3
  uid: 17c36c44-ca51-4235-aaea-bff8ff4bf8d0
type: structure
