name: deploy
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - run: |
                echo ${{ github.workspace }}
                echo $GITHUB_WORKSPACE
            - name: deploy
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: "-rlgoDzvc -i --delete"
                  SOURCE: ""
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
                  TARGET: ${{ secrets.TARGET }}
                  EXCLUDE: "/.ddev/, /.github/, /storage/, /vendor/, /web/cpresources/, /web/public/, '/web/.htaccess, '/.env/, /.gitgnore, /.parcel-cache, /node_modules"
                  SCRIPT_BEFORE: |
                    /opt/php82/bin/php craft off
                  SCRIPTZ_AFTER: |
                    /opt/php82/bin/php craft up